---
spring:
  datasource:
    url: jdbc:mysql://150.158.99.245/library_system?useSSL=false
    username: root
    password: fzk686292.
    driver-class-name: com.mysql.cj.jdbc.Driver


  config:
    activate:
      on-profile: dev
server:
  port: 8000

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
#  api-docs:
#    path: /api-docs
---

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/library_system?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  config:
    activate:
      on-profile: pro
server:
  port: 8080

---

spring:
  profiles:
    active: dev