---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/library_system?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  config:
    activate:
      on-profile: pro
    main:
        allow-circular-references: true
server:
  port: 8080

---

spring:
  profiles:
    active: pro